version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.12
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket sctdms --output-template-file packaged.yml
artifacts:
  files:
    - packaged.yml
