version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.12
  build:
    commands:
      - pip install -r requirements.txt -t .
      - aws cloudformation package --template-file template.yaml --s3-bucket sctdms --output-template-file template-out.yaml
artifacts:
  files:
    - template.yaml
    - template-out.yaml
